# Generated by Django 6.1.1 on 2026-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_container_sensorreading_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
